# ARMADILLO_INCLUDE_DIR = armadillo
# ARMADILLO_LIBRARIES = libarmadillo.so
# ARMADILLO_FOUND = true if Armadillo is found

IF(ARMADILLO_INCLUDE_DIRS)
  FIND_PATH(ARMADILLO_INCLUDE_DIR armadillo ${ARMADILLO_INCLUDE_DIRS})
  FIND_LIBRARY(ARMADILLO_LIBRARY armadillo ${ARMADILLO_LIBRARY_DIRS})
ELSE(ARMADILLO_INCLUDE_DIRS)
    SET(TRIAL_PATHS
      /usr/include
      /usr/local/include
      $ENV{ARMADILLO_INC}
    )
    SET(TRIAL_LIBRARY_PATHS
      /usr/lib
      /usr/lib64
      /usr/local/lib
      /usr/local/lib64
      $ENV{ARMADILLO_DIR}
      )
    FIND_PATH(ARMADILLO_INCLUDE_DIR armadillo ${TRIAL_PATHS})
    FIND_LIBRARY(ARMADILLO_LIBRARY armadillo ${TRIAL_LIBRARY_PATHS})
ENDIF(ARMADILLO_INCLUDE_DIRS)
set(ARMADILLO_INCLUDE_DIRS ${ARMADILLO_INCLUDE_DIR} )
set(ARMADILLO_LIBRARIES ${ARMADILLO_LIBRARY} )

IF(ARMADILLO_INCLUDE_DIR AND ARMADILLO_LIBRARIES)
  MESSAGE(STATUS "ARMADILLO_INCLUDE_DIR=${ARMADILLO_INCLUDE_DIR}")
  MESSAGE(STATUS "ARMADILLO_LIBRARIES=${ARMADILLO_LIBRARIES}")
  SET(ARMADILLO_FOUND TRUE)
ELSE()
  MESSAGE("ARMADILLO NOT found.")
  SET(ARMADILLO_FOUND FALSE)
ENDIF()

MARK_AS_ADVANCED(
   ARMADILLO_INCLUDE_DIR
   ARMADILLO_LIBRARIES
   ARMADILLO_FOUND
)
